### ISSUE TITLE
traffic-control-openshift: VM kworker takes all cpu

### ISSUE THREAD

**Issue by alban** [kinvolk/demo#11]
When using the VM from https://github.com/openshift-evangelists/vagrant-origin with a new kernel, at some point kworker takes 100% of cpu and it becomes unusable.

Workaround from https://github.com/docker/docker/issues/3280:

Edit /etc/sysconfig/docker-storage:
```
DOCKER_STORAGE_OPTIONS=--storage-opt dm.blkdiscard=false
```

And reboot (to restart Docker).

**Comment by alepuccetti** [comment]
This https://github.com/kinvolk/openshift-evangelists-vagrant-origin/pull/1 fixes
